import { useState, useEffect } from "react";
import {
  Upload,
  Leaf,
  AlertCircle,
  CheckCircle2,
  Info,
  Stethoscope,
  ShieldCheck,
  FlaskConical,
  Sparkles,
} from "lucide-react";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:10000";

// ── Translations ───────────────────────────────────────────────────────────────
const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    app_title: "Tomato Leaf Disease Detector",
    app_desc: "Upload a leaf image — AI predicts the disease instantly, then click Get Analysis for expert disease insights.",
    upload_img: "Upload Image",
    drag_drop: "Drag and drop a leaf image",
    supported: "JPG, PNG, WEBP supported",
    browse: "Browse Files",
    upload_another: "Upload Another Image",
    running_model: "Running model prediction...",
    no_disease: "No Disease Detected",
    disease_detected: "Disease Detected",
    conf: "Confidence:",
    get_analysis: "Get Analysis",
    re_analyze: "Re-analyze",
    loading_analysis: "Loading analysis...",
    analysis_title: "Disease Analysis",
    disease_detected_click: "Disease detected! Click Get Analysis to view detailed insights.",
    try_again: "Try Again",
    powered_by: "Powered by Groq AI (llama-3.1-8b)",
    footer: "Disease information is generated by AI and is for educational reference only. Always consult an agronomist.",
    server_online: "Backend Connected",
    server_offline: "Backend Offline",
    server_checking: "Checking Server..."
  },
  hi: {
    app_title: "टमाटर पत्ता रोग डिटेक्टर",
    app_desc: "एक पत्ती की छवि अपलोड करें - AI तुरंत रोग की भविष्यवाणी करता है, फिर विशेषज्ञ अंतर्दृष्टि के लिए विश्लेषण प्राप्त करें पर क्लिक करें।",
    upload_img: "छवि अपलोड करें",
    drag_drop: "एक पत्ती की छवि यहां खींचें और छोड़ें",
    supported: "JPG, PNG, WEBP समर्थित",
    browse: "फ़ाइलें ब्राउज़ करें",
    upload_another: "दूसरी छवि अपलोड करें",
    running_model: "मॉडल भविष्यवाणी चल रही है...",
    no_disease: "कोई बीमारी नहीं मिली",
    disease_detected: "बीमारी का पता चला",
    conf: "आत्मविश्वास:",
    get_analysis: "विश्लेषण प्राप्त करें",
    re_analyze: "पुनः विश्लेषण करें",
    loading_analysis: "विश्लेषण लोड हो रहा है...",
    analysis_title: "रोग विश्लेषण",
    disease_detected_click: "बीमारी का पता चला! विस्तृत अंतर्दृष्टि देखने के लिए विश्लेषण प्राप्त करें पर क्लिक करें।",
    try_again: "पुनः प्रयास करें",
    powered_by: "Groq AI द्वारा संचालित",
    footer: "रोग की जानकारी AI द्वारा उत्पन्न की जाती है और केवल शैक्षिक संदर्भ के लिए है।",
    server_online: "बैकएंड कनेक्टेड",
    server_offline: "बैकएंड ऑफ़लाइन",
    server_checking: "सर्वर की जाँच हो रही है..."
  },
  ta: {
    app_title: "தக்காளி இலை நோய் கண்டறிதல்",
    app_desc: "ஒரு இலையின் படத்தைப் பதிவேற்றவும் - AI உடனடியாக நோயைக் கணிக்கிறது, நிபுணர் பகுப்பாய்வைப் பெற கிளிக் செய்யவும்.",
    upload_img: "படம் பதிவேற்று",
    drag_drop: "இலை படத்தை இங்கே இழுத்து விடவும்",
    supported: "JPG, PNG, WEBP அனுமதிக்கப்படுகிறது",
    browse: "கோப்புகளைத் தேடு",
    upload_another: "மற்றொரு படத்தைப் பதிவேற்று",
    running_model: "கணிப்பு இயங்குகிறது...",
    no_disease: "நோய் கண்டறியப்படவில்லை",
    disease_detected: "நோய் கண்டறியப்பட்டுள்ளது",
    conf: "நம்பிக்கை:",
    get_analysis: "பகுப்பாய்வு பெறுக",
    re_analyze: "மீண்டும் பகுப்பாய்வு செய்க",
    loading_analysis: "பகுப்பாய்வு ஏற்றுகிறது...",
    analysis_title: "நோய் பகுப்பாய்வு",
    disease_detected_click: "நோய் கண்டறியப்பட்டுள்ளது! விரிவான பகுப்பாய்வைப் பெற கிளிக் செய்யவும்.",
    try_again: "மீண்டும் முயற்சிக்கவும்",
    powered_by: "Groq AI மூலம் வழங்கப்படுகிறது",
    footer: "நோய் தகவல்கள் கல்விக் குறிப்புக்காக மட்டுமே. தீவிர பிரச்சனைகளுக்கு நிபுணரை அணுகவும்.",
    server_online: "சர்வர் இணைக்கப்பட்டுள்ளது",
    server_offline: "சர்வர் ஆஃப்லைன்",
    server_checking: "சர்வர் சரிபார்க்கப்படுகிறது..."
  },
  te: {
    app_title: "టొమాటో ఆకు వ్యాధి డిటెక్టర్",
    app_desc: "ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి - AI వ్యాధిని తక్షణమే అంచనా వేస్తుంది, తర్వాత నిపుణుల విశ్లేషణ కోసం క్లిక్ చేయండి.",
    upload_img: "చిత్రాన్ని అప్‌లోడ్ చేయండి",
    drag_drop: "ఆకు చిత్రాన్ని ఇక్కడ లాగి వదలండి",
    supported: "JPG, PNG, WEBP మద్దతు ఇస్తుంది",
    browse: "ఫైల్‌లను బ్రౌజ్ చేయండి",
    upload_another: "మరొక చిత్రాన్ని అప్‌లోడ్ చేయండి",
    running_model: "మోడల్ అంచనా వేస్తోంది...",
    no_disease: "ఎటువంటి వ్యాధి కనుగొనబడలేదు",
    disease_detected: "వ్యాధి కనుగొనబడింది",
    conf: "విశ్వాసం:",
    get_analysis: "విశ్లేషణ పొందండి",
    re_analyze: "మళ్లీ విశ్లేషించండి",
    loading_analysis: "విశ్లేషణ లోడ్ అవుతోంది...",
    analysis_title: "వ్యాధి విశ్లేషణ",
    disease_detected_click: "వ్యాధి కనుగొనబడింది! వివరణాత్మక విశ్లేషణ కోసం క్లిక్ చేయండి.",
    try_again: "మళ్ళీ ప్రయత్నించండి",
    powered_by: "Groq AI ద్వారా ఆధారితం",
    footer: "వ్యాధి సమాచారం AI సిఫార్సు మాత్రమే. నిపుణుడిని సంప్రదించండి.",
    server_online: "సర్వర్ కనెక్ట్ చేయబడింది",
    server_offline: "సర్వర్ ఆఫ్‌లైన్",
    server_checking: "సర్వర్‌ తనిఖీ చేస్తోంది..."
  },
  kn: {
    app_title: "ಟೊಮೆಟೊ ಎಲೆ ರೋಗ ಪತ್ತೆಗಾರ",
    app_desc: "ಎಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ - AI ರೋಗವನ್ನು ತಕ್ಷಣ ಅಂದಾಜಿಸುತ್ತದೆ, ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಲು ಕ್ಲಿಕ್ ಮಾಡಿ.",
    upload_img: "ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    drag_drop: "ಎಲೆಯ ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಎಳೆಯಿರಿ",
    supported: "JPG, PNG, WEBP ಬೆಂಬಲಿತವಾಗಿದೆ",
    browse: "ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
    upload_another: "ಮತ್ತೊಂದು ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    running_model: "ಮುನ್ಸೂಚನೆ ನಡೆಯುತ್ತಿದೆ...",
    no_disease: "ಯಾವುದೇ ರೋಗ ಪತ್ತೆಯಾಗಿಲ್ಲ",
    disease_detected: "ರೋಗ ಪತ್ತೆಯಾಗಿದೆ",
    conf: "ವಿಶ್ವಾಸ:",
    get_analysis: "ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ",
    re_analyze: "ಮತ್ತೆ ವಿಶ್ಲೇಷಿಸಿ",
    loading_analysis: "ವಿಶ್ಲೇಷಣೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    analysis_title: "ರೋಗ ವಿಶ್ಲೇಷಣೆ",
    disease_detected_click: "ರೋಗ ಪತ್ತೆಯಾಗಿದೆ! ವಿವರವಾದ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    try_again: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    powered_by: "Groq AI ನಿಂದ ನಡೆಸಲ್ಪಡುತ್ತಿದೆ",
    footer: "ಸಮಾಚಾರ ಕೇವಲ ಶಿಕ್ಷಣ ರೇಫರೆನ್ಸ್ ಮಾತ್ರ. ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    server_online: "ಸರ್ವರ್ ಸಂಪರ್ಕಗೊಂಡಿದೆ",
    server_offline: "ಸರ್ವರ್ ಆಫ್‌ಲೈನ್ ಆಗಿದೆ",
    server_checking: "ಸರ್ವರ್ ಪರಿಶೀಲಿಸುತ್ತಿದೆ..."
  },
  ml: {
    app_title: "തക്കാളി ഇല രോഗ നിർണ്ണയ ഉപകരണം",
    app_desc: "ഒരു ഇലയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക - AI പെട്ടെന്ന് രോഗം പ്രവചിക്കുന്നു, കൂടുതൽ വിവരങ്ങൾക്ക് ക്ലിക്ക് ചെയ്യുക.",
    upload_img: "ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    drag_drop: "ചിത്രം ഇവിടെ വലിച്ചിടുക",
    supported: "JPG, PNG, WEBP പിന്തുണയ്ക്കുന്നു",
    browse: "ഫയലുകൾ തിരയുക",
    upload_another: "മറ്റൊരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    running_model: "പ്രവചനം നടക്കുന്നു...",
    no_disease: "രോഗമൊന്നും കണ്ടെത്തിയില്ല",
    disease_detected: "രോഗം കണ്ടെത്തി",
    conf: "ആത്മവിശ്വാസം:",
    get_analysis: "വിശകലനം നേടുക",
    re_analyze: "വീണ്ടും വിശകലനം ചെയ്യുക",
    loading_analysis: "വിശകലനം ലോഡുചെയ്യുന്നു...",
    analysis_title: "രോഗ വിശകലനം",
    disease_detected_click: "രോഗം കണ്ടെത്തി! വിശദമായ വിവരങ്ങൾക്ക് ക്ലിക്ക് ചെയ്യുക.",
    try_again: "വീണ്ടും ശ്രമിക്കുക",
    powered_by: "Groq AI ആണ് നൽകുന്നത്",
    footer: "വിവരങ്ങൾ അവലംബത്തിനു മാത്രമുള്ളതാണ്. ഒരു വിദഗ്ദ്ധനെ സമീപിക്കുക.",
    server_online: "സെർവർ കണക്റ്റുചെയ്‌തു",
    server_offline: "സെർവർ ഓഫ്‌ലൈൻ",
    server_checking: "സെർവർ പരിശോധിക്കുന്നു..."
  },
  mr: {
    app_title: "टोमॅटो पान रोग शोधक",
    app_desc: "पानाची प्रतिमा अपलोड करा - AI त्वरित रोगाचा अंदाज लावते, नंतर विश्लेषण मिळवा वर क्लिक करा.",
    upload_img: "प्रतिमा अपलोड करा",
    drag_drop: "प्रतिमा येथे ड्रॅग आणि ड्रॉप करा",
    supported: "JPG, PNG, WEBP समर्थित",
    browse: "फायली ब्राउझ करा",
    upload_another: "दुसरी प्रतिमा अपलोड करा",
    running_model: "अंदाज चालत आहे...",
    no_disease: "कोणताही रोग आढळला नाही",
    disease_detected: "रोग आढळला",
    conf: "आत्मविश्वास:",
    get_analysis: "विश्लेषण मिळवा",
    re_analyze: "पुन्हा विश्लेषण करा",
    loading_analysis: "विश्लेषण लोड होत आहे...",
    analysis_title: "रोग विश्लेषण",
    disease_detected_click: "रोग आढळला! सविस्तर माहितीसाठी क्लिक करा.",
    try_again: "पुन्हा प्रयत्न करा",
    powered_by: "Groq AI द्वारे समर्थित",
    footer: "माहिती केवळ शैक्षणिक संदर्भासाठी आहे. तज्ञाचा सल्ला घ्या.",
    server_online: "सर्व्हर कनेक्टेड",
    server_offline: "सर्व्हर ऑफलाईन",
    server_checking: "सर्व्हर तपासत आहे..."
  },
  bn: {
    app_title: "টমেটো পাতার রোগ শনাক্তকারী",
    app_desc: "পাতার ছবি আপলোড করুন - AI দ্রুত রোগ নির্ণয় করে, তারপর বিস্তারিত বিশ্লেষণের জন্য ক্লিক করুন।",
    upload_img: "ছবি আপলোড করুন",
    drag_drop: "এখানে ছবি টেনে আনুন",
    supported: "JPG, PNG, WEBP সমর্থিত",
    browse: "ফাইলগুলি ব্রাউজ করুন",
    upload_another: "অন্য একটি ছবি আপলোড করুন",
    running_model: "মডেল পূর্বাভাস চলছে...",
    no_disease: "কোনো রোগ সনাক্ত হয়নি",
    disease_detected: "রোগ শনাক্ত হয়েছে",
    conf: "বিশ্বাস:",
    get_analysis: "বিশ্লেষণ পান",
    re_analyze: "পুনরায় বিশ্লেষণ করুন",
    loading_analysis: "বিশ্লেষণ লোড হচ্ছে...",
    analysis_title: "রোগ বিশ্লেষণ",
    disease_detected_click: "রোগ শনাক্ত হয়েছে! বিস্তারিত জানতে ক্লিক করুন।",
    try_again: "আবার চেষ্টা করুন",
    powered_by: "Groq AI দ্বারা চালিত",
    footer: "এই তথ্য শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে। বিশেষজ্ঞের পরামর্শ নিন।",
    server_online: "সার্ভার সংযুক্ত",
    server_offline: "সার্ভার অফলাইন",
    server_checking: "সার্ভার পরীক্ষা করা হচ্ছে..."
  },
  gu: {
    app_title: "ટામેટા પર્ણ રોગ ડિટેક્ટર",
    app_desc: "પર્ણની છબી અપલોડ કરો - AI તરત રોગ શોધી કાઢે છે, પછી વિગતવાર માહિતી માટે ક્લિક કરો.",
    upload_img: "છબી અપલોડ કરો",
    drag_drop: "અહીં છબી ખેંચીને મૂકો",
    supported: "JPG, PNG, WEBP આધારિત",
    browse: "ફાઇલો બ્રાઉઝ કરો",
    upload_another: "બીજી છબી અપલોડ કરો",
    running_model: "મોડેલ આગાહી ચાલી રહી છે...",
    no_disease: "કોઈ રોગ મળ્યો નથી",
    disease_detected: "રોગ મળ્યો",
    conf: "આત્મવિશ્વાસ:",
    get_analysis: "વિશ્લેષણ મેળવો",
    re_analyze: "ફરીથી વિશ્લેષણ કરો",
    loading_analysis: "વિશ્લેષણ લોડ થઈ રહ્યું છે...",
    analysis_title: "રોગ વિશ્લેષણ",
    disease_detected_click: "રોગ મળ્યો! વિગતવાર માહિતી જોવા માટે ક્લિક કરો.",
    try_again: "ફરી ત્રાય કરો",
    powered_by: "Groq AI આધારિત",
    footer: "માહિતી ફક્ત શૈક્ષણિક હેતુ છે. નિષ્ણાતની સલાહ લો.",
    server_online: "સર્વર કનેક્ટેડ",
    server_offline: "સર્વર ઓફલાઇન",
    server_checking: "સર્વર તપાસી રહ્યા છીએ..."
  },
  pa: {
    app_title: "ਟਮਾਟਰ ਪੱਤੇ ਦੀ ਬਿਮਾਰੀ ਦਾ ਡਿਟੈਕਟਰ",
    app_desc: "ਇੱਕ ਪੱਤੇ ਦੀ ਤਸਵੀਰ ਅਪਲੋਡ ਕਰੋ - AI ਤੁਰੰਤ ਬਿਮਾਰੀ ਦਾ ਪਤਾ ਲਗਾਉਂਦਾ ਹੈ।",
    upload_img: "ਤਸਵੀਰ ਅਪਲੋਡ ਕਰੋ",
    drag_drop: "ਇੱਥੇ ਤਸਵੀਰ ਖਿੱਚੋ ਅੱਤੇ ਸੁੱਟੋ",
    supported: "JPG, PNG, WEBP ਸਮਰਥਿਤ",
    browse: "ਫਾਈਲਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ",
    upload_another: "ਕੋਈ ਹੋਰ ਤਸਵੀਰ ਅਪਲੋਡ ਕਰੋ",
    running_model: "ਮਾਡਲ ਭਵਿੱਖਬਾਣੀ ਚੱਲ ਰਹੀ ਹੈ...",
    no_disease: "ਕੋਈ ਬਿਮਾਰੀ ਨਹੀਂ ਮਿਲੀ",
    disease_detected: "ਬਿਮਾਰੀ ਦਾ ਪਤਾ ਲੱਗਾ",
    conf: "ਭਰੋਸਾ:",
    get_analysis: "ਵਿਸ਼ਲੇਸ਼ਣ ਪ੍ਰਾਪਤ ਕਰੋ",
    re_analyze: "ਦੁਬਾਰਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    loading_analysis: "ਵਿਸ਼ਲੇਸ਼ਣ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    analysis_title: "ਬਿਮਾਰੀ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ",
    disease_detected_click: "ਬਿਮਾਰੀ ਮਿਲੀ! ਵਿਸਤ੍ਰਿਤ ਜਾਣਕਾਰੀ ਲਈ ਕਲਿਕ ਕਰੋ।",
    try_again: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    powered_by: "Groq AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ",
    footer: "ਇਹ ਜਾਣਕਾਰੀ ਸਿਰਫ ਸਿੱਖਿਆ ਲਈ ਹੈ। ਮਾਹਰ ਨਾਲ ਸਲਾਹ ਕਰੋ।",
    server_online: "ਸਰਵਰ ਜੁੜਿਆ ਹੋਇਆ ਹੈ",
    server_offline: "ਸਰਵਰ ਔਫਲਾਈਨ ਹੈ",
    server_checking: "ਸਰਵਰ ਦੀ ਜਾਂਚ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ..."
  }
};

const t = (lang: string, key: string) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS["en"][key] || key;

interface PredictionResult {
  disease: string;
  confidence: number;
}

interface AnalysisResult {
  description: string;
  symptoms: string[];
  prevention: string[];
  treatment: string[];
}

// ── Helper Components ──────────────────────────────────────────────────────────

function InfoList({
  icon,
  title,
  items,
  bulletColor,
  bullet,
}: {
  icon: React.ReactNode;
  title: string;
  items: string[];
  bulletColor: string;
  bullet: string;
}) {
  return (
    <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-4">
      <h4 className="font-semibold text-gray-800 mb-3 flex items-center gap-2 text-sm uppercase tracking-wide">
        {icon}
        {title}
      </h4>
      <ul className="space-y-2">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
            <span className={`${bulletColor} mt-0.5 flex-shrink-0 font-bold`}>
              {bullet === "num" ? `${i + 1}.` : bullet}
            </span>
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// ── Main App ───────────────────────────────────────────────────────────────────

export default function App() {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [prediction, setPrediction] = useState<PredictionResult | null>(null);
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);

  const [language, setLanguage] = useState<string>("en");

  const [isPredicting, setIsPredicting] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const [predictError, setPredictError] = useState<string | null>(null);
  const [analyzeError, setAnalyzeError] = useState<string | null>(null);

  const [isDragging, setIsDragging] = useState(false);
  const [serverStatus, setServerStatus] = useState<"checking" | "online" | "offline">("checking");

  // ── Server heartbeat ────────────────────────────────────────────────────────
  useEffect(() => {
    const check = async () => {
      try {
        const res = await fetch(`${API_BASE}/`);
        setServerStatus(res.ok ? "online" : "offline");
      } catch {
        setServerStatus("offline");
      }
    };
    check();
    const t = setInterval(check, 5000);
    return () => clearInterval(t);
  }, []);

  // ── ML Prediction ────────────────────────────────────────────────────────────
  const handleImageUpload = async (file: File) => {
    const reader = new FileReader();
    reader.onload = async (e) => {
      setSelectedImage(e.target?.result as string);
      setPrediction(null);
      setAnalysis(null);
      setPredictError(null);
      setAnalyzeError(null);
      setIsPredicting(true);

      const formData = new FormData();
      formData.append("file", file);

      try {
        const res = await fetch(`${API_BASE}/predict`, {
          method: "POST",
          body: formData,
        });
        if (!res.ok) {
          const err = await res.json().catch(() => ({}));
          throw new Error(err.error || `Server error: ${res.status}`);
        }
        const data = await res.json();
        if (data.error) throw new Error(data.error);
        setPrediction({ disease: data.disease, confidence: data.confidence });
      } catch (err) {
        setPredictError(err instanceof Error ? err.message : "Prediction failed.");
      } finally {
        setIsPredicting(false);
      }
    };
    reader.readAsDataURL(file);
  };

  // ── Gemini/Groq Analysis ──────────────────────────────────────────────────────────
  const handleGetAnalysis = async (targetLang: string = language) => {
    if (!prediction) return;
    setAnalyzeError(null);
    setIsAnalyzing(true);

    try {
      const res = await fetch(`${API_BASE}/analyze`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ disease: prediction.disease, lang: targetLang }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || `Server error: ${res.status}`);
      }
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setAnalysis({
        description: data.description || "",
        symptoms: data.symptoms || [],
        prevention: data.prevention || [],
        treatment: data.treatment || [],
      });
    } catch (err) {
      setAnalyzeError(err instanceof Error ? err.message : "Analysis failed.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  // ── File input handlers ──────────────────────────────────────────────────────
  const handleFileInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file && file.type.startsWith("image/")) handleImageUpload(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files[0];
    if (file && file.type.startsWith("image/")) handleImageUpload(file);
  };

  const resetApp = () => {
    setSelectedImage(null);
    setPrediction(null);
    setAnalysis(null);
    setPredictError(null);
    setAnalyzeError(null);
    setIsPredicting(false);
    setIsAnalyzing(false);
  };

  const handleLanguageChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newLang = e.target.value;
    setLanguage(newLang);
    if (prediction && analysis) {
      handleGetAnalysis(newLang);
    }
  };

  const isHealthy = prediction?.disease === "Healthy";

  // ── Render ───────────────────────────────────────────────────────────────────
  return (
    <div className="min-h-screen relative bg-gradient-to-br from-green-50 to-emerald-100 p-4 md:p-8">
      <div className="max-w-6xl mx-auto">

        {/* Server Status Dot */}
        <div 
          className="absolute top-4 left-4 md:top-6 md:left-6 transition-all"
          title={
            serverStatus === "online" ? t(language, "server_online") :
            serverStatus === "offline" ? t(language, "server_offline") :
            t(language, "server_checking")
          }
        >
          <div
            className={`w-3.5 h-3.5 md:w-4 md:h-4 rounded-full shadow-sm ring-2 ring-green-100 ${
              serverStatus === "online" ? "bg-emerald-500"
              : serverStatus === "offline" ? "bg-red-500"
              : "bg-amber-400 animate-pulse"
            }`}
          />
        </div>

        {/* Header */}
        <div className="text-center mb-8 pt-2">
          <div className="mb-4 flex justify-center">
            {/* Global Language Selector */}
            <select
              value={language}
              onChange={handleLanguageChange}
              disabled={isAnalyzing}
              className="px-3 py-1.5 rounded-full text-sm font-medium shadow border border-gray-200 outline-none focus:ring-2 focus:ring-green-500 bg-white text-gray-700 hover:bg-gray-50 transition-colors disabled:opacity-50 appearance-none pr-8 relative cursor-pointer"
              style={{
                backgroundImage: `url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e")`,
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'right 0.6rem center',
                backgroundSize: '1em'
              }}
            >
              <option value="en">English</option>
              <option value="hi">हिंदी (Hindi)</option>
              <option value="ta">தமிழ் (Tamil)</option>
              <option value="te">తెలుగు (Telugu)</option>
              <option value="kn">ಕನ್ನಡ (Kannada)</option>
              <option value="ml">മലയാളം (Malayalam)</option>
              <option value="mr">मराठी (Marathi)</option>
              <option value="bn">বাংলা (Bengali)</option>
              <option value="gu">ગુજરાતી (Gujarati)</option>
              <option value="pa">ਪੰਜਾਬੀ (Punjabi)</option>
            </select>
          </div>
          <div className="flex items-center justify-center gap-3 mb-2">
            <Leaf className="w-9 h-9 text-green-600" />
            <h1 className="text-4xl font-bold text-gray-800">
              {t(language, "app_title")}
            </h1>
          </div>
          <p className="text-gray-500 text-sm max-w-xl mx-auto">
            {t(language, "app_desc")}
          </p>
        </div>

        {/* Prediction Error */}
        {predictError && (
          <div className="mb-6 rounded-2xl shadow p-5 text-center bg-gradient-to-r from-orange-500 to-red-500">
            <div className="flex items-center justify-center gap-2 mb-1">
              <AlertCircle className="w-5 h-5 text-white" />
              <h2 className="text-lg font-bold text-white">Prediction Failed</h2>
            </div>
            <p className="text-white/90 text-sm">{predictError}</p>
          </div>
        )}

        {/* Result Banner — shown after prediction */}
        {prediction && (
          <div
            className={`mb-6 rounded-2xl shadow-lg p-6 text-center transition-all ${
              isHealthy
                ? "bg-gradient-to-r from-green-500 to-emerald-600"
                : "bg-gradient-to-r from-red-500 to-rose-600"
            }`}
          >
            <div className="flex items-center justify-center gap-3 mb-2">
              {isHealthy ? (
                <CheckCircle2 className="w-7 h-7 text-white" />
              ) : (
                <AlertCircle className="w-7 h-7 text-white" />
              )}
              <h2 className="text-2xl font-bold text-white">
                {isHealthy ? t(language, "no_disease") : t(language, "disease_detected")}
              </h2>
            </div>
            <p className="text-4xl font-extrabold text-white mb-1">
              {prediction.disease}
            </p>
            <p className="text-white/80 text-base mb-4">
              {t(language, "conf")} {prediction.confidence}%
            </p>

            {/* Confidence bar */}
            <div className="w-full max-w-xs mx-auto bg-white/30 rounded-full h-2 mb-5">
              <div
                className="h-2 bg-white rounded-full transition-all duration-700"
                style={{ width: `${prediction.confidence}%` }}
              />
            </div>

            {/* Get Analysis Button */}
            {!analysis && !isAnalyzing && (
              <button
                onClick={() => handleGetAnalysis(language)}
                className="inline-flex items-center gap-2 bg-white text-gray-800 font-semibold px-6 py-2.5 rounded-full shadow hover:shadow-md hover:scale-105 active:scale-100 transition-all duration-200"
              >
                <Sparkles className="w-4 h-4 text-yellow-500" />
                {t(language, "get_analysis")}
              </button>
            )}

            {/* Analyzing spinner inside banner */}
            {isAnalyzing && (
              <div className="flex items-center justify-center gap-3 text-white">
                <div className="w-5 h-5 border-2 border-white/40 border-t-white rounded-full animate-spin" />
                <span className="font-medium">{t(language, "loading_analysis")}</span>
              </div>
            )}

            {/* Re-analyze button if analysis is already shown */}
            {analysis && !isAnalyzing && (
              <button
                onClick={() => handleGetAnalysis(language)}
                className="inline-flex items-center gap-2 bg-white/20 text-white border border-white/40 font-medium px-5 py-2 rounded-full hover:bg-white/30 transition-all text-sm"
              >
                <Sparkles className="w-4 h-4" />
                {t(language, "re_analyze")}
              </button>
            )}
          </div>
        )}

        {/* Main Grid: Upload + Results */}
        <div className="grid md:grid-cols-2 gap-6">

          {/* Upload Panel */}
          <div className="bg-white rounded-2xl shadow-lg p-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-4 flex items-center gap-2">
              <Upload className="w-5 h-5 text-green-600" />
              {t(language, "upload_img")}
            </h2>

            {!selectedImage ? (
              <div
                className={`border-2 border-dashed rounded-xl p-10 text-center transition-colors cursor-pointer ${
                  isDragging
                    ? "border-green-500 bg-green-50"
                    : "border-gray-300 bg-gray-50 hover:border-green-400 hover:bg-green-50"
                }`}
                onDrop={handleDrop}
                onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                onDragLeave={() => setIsDragging(false)}
              >
                <Upload className="w-12 h-12 mx-auto mb-3 text-gray-400" />
                <p className="text-gray-600 font-medium mb-1">
                  {t(language, "drag_drop")}
                </p>
                <p className="text-gray-400 text-xs mb-5">{t(language, "supported")}</p>
                <label className="inline-block">
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleFileInput}
                    className="hidden"
                  />
                  <span className="cursor-pointer bg-green-600 text-white px-6 py-2.5 rounded-lg hover:bg-green-700 transition-colors inline-block font-medium text-sm">
                    {t(language, "browse")}
                  </span>
                </label>
              </div>
            ) : (
              <div>
                <div className="rounded-xl overflow-hidden mb-4 border border-gray-100 shadow-sm">
                  <img
                    src={selectedImage}
                    alt="Uploaded tomato leaf"
                    className="w-full h-auto"
                  />
                </div>
                <button
                  onClick={resetApp}
                  className="w-full bg-gray-100 text-gray-700 py-2.5 rounded-lg hover:bg-gray-200 transition-colors font-medium text-sm"
                >
                  {t(language, "upload_another")}
                </button>
              </div>
            )}

            {/* Predicting spinner */}
            {isPredicting && (
              <div className="mt-5 flex flex-col items-center gap-2">
                <div className="w-8 h-8 border-4 border-green-200 border-t-green-600 rounded-full animate-spin" />
                <p className="text-gray-500 text-sm">{t(language, "running_model")}</p>
              </div>
            )}
          </div>

          {/* Analysis Panel */}
          <div className="bg-white rounded-2xl shadow-lg p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
                <Info className="w-5 h-5 text-green-600" />
                {t(language, "analysis_title")}
              </h2>
            </div>

            {/* Empty state */}
            {!prediction && !isPredicting && (
              <div className="flex flex-col items-center justify-center h-64 text-gray-400">
                <Leaf className="w-14 h-14 mb-3 opacity-40" />
                <p className="text-sm text-center">
                  Upload a leaf image to detect disease,<br />
                  then click <strong>Get Analysis</strong> for details.
                </p>
              </div>
            )}

            {/* Waiting for user to click button */}
            {prediction && !isAnalyzing && !analysis && !analyzeError && (
              <div className="flex flex-col items-center justify-center h-64 text-gray-400">
                <Sparkles className="w-12 h-12 mb-3 text-yellow-400 opacity-80" />
                <p className="text-sm text-center text-gray-500">
                  {t(language, "disease_detected_click")}
                </p>
              </div>
            )}

            {/* Analyzing spinner in panel */}
            {isAnalyzing && (
              <div className="flex flex-col items-center justify-center h-64 text-gray-500">
                <div className="w-10 h-10 border-4 border-yellow-200 border-t-yellow-500 rounded-full animate-spin mb-4" />
                <p className="text-sm font-medium">{t(language, "loading_analysis")}</p>
                <p className="text-xs text-gray-400 mt-1">This may take a few seconds</p>
              </div>
            )}

            {/* Analysis error */}
            {analyzeError && !isAnalyzing && (
              <div className="flex flex-col items-center justify-center h-48 text-center">
                <AlertCircle className="w-10 h-10 text-red-400 mb-3" />
                <p className="text-sm font-semibold text-red-600 mb-1">Analysis Failed</p>
                <p className="text-xs text-gray-500 max-w-xs">{analyzeError}</p>
                <button
                  onClick={() => handleGetAnalysis(language)}
                  className="mt-4 text-sm bg-red-50 text-red-600 border border-red-200 px-4 py-2 rounded-lg hover:bg-red-100 transition-colors"
                >
                  {t(language, "try_again")}
                </button>
              </div>
            )}

            {/* Analysis Results */}
            {analysis && !isAnalyzing && (
              <div className="space-y-4 overflow-y-auto max-h-[480px] pr-1">

                {/* Description */}
                {analysis.description && (
                  <div className="bg-blue-50 border border-blue-100 rounded-xl p-4">
                    <h4 className="text-xs font-semibold uppercase tracking-wide text-blue-600 mb-1.5 flex items-center gap-1.5">
                      <Info className="w-3.5 h-3.5" /> About
                    </h4>
                    <p className="text-sm text-gray-700 leading-relaxed">{analysis.description}</p>
                  </div>
                )}

                {/* Symptoms */}
                {analysis.symptoms.length > 0 && (
                  <InfoList
                    icon={<Stethoscope className="w-3.5 h-3.5 text-red-500" />}
                    title="Symptoms"
                    items={analysis.symptoms}
                    bulletColor="text-red-400"
                    bullet="•"
                  />
                )}

                {/* Prevention */}
                {analysis.prevention.length > 0 && (
                  <InfoList
                    icon={<ShieldCheck className="w-3.5 h-3.5 text-green-600" />}
                    title="Prevention"
                    items={analysis.prevention}
                    bulletColor="text-green-500"
                    bullet="✓"
                  />
                )}

                {/* Treatment */}
                {analysis.treatment.length > 0 && (
                  <InfoList
                    icon={<FlaskConical className="w-3.5 h-3.5 text-blue-500" />}
                    title="Treatment"
                    items={analysis.treatment}
                    bulletColor="text-blue-400"
                    bullet="num"
                  />
                )}

                <p className="text-center text-xs text-gray-400 pt-1">
                  {t(language, "powered_by")}
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 bg-white rounded-xl shadow p-4 text-center text-xs text-gray-400">
          {t(language, "footer")}
        </div>

      </div>
    </div>
  );
}
